from structures.orderedlist import OrderedList

my_list = OrderedList()
my_list.add(31)
my_list.add(77)
my_list.add(17)
my_list.add(17)
my_list.add(17)
my_list.add(93)
my_list.add(26)
my_list.add(54)

# print(my_list.pop(5))
# print(my_list.pop())
# print(my_list.pop())
# print(my_list.pop())
# print(my_list.pop())
# print(my_list.pop())
# print(my_list.pop())
# print(my_list.pop())
print(my_list.search(54))
